project_id = "qmpikyymjcnmocjfmvxs"

[functions.menu-import-ai]
verify_jwt = false

[functions.menu-enhance-image]
verify_jwt = false

[functions.menu-generate-video]
verify_jwt = false

[functions.stripe-onboarding]
verify_jwt = false

[functions.stripe-create-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.asaas-checkout-plan]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false
